// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'ejemplonumeros-968be',
    appId: '1:926947830123:web:f97d794dff4b2f2c8e442e',
    storageBucket: 'ejemplonumeros-968be.appspot.com',
    apiKey: 'AIzaSyBsUZdk4q9wJhYRoIS9goFNRFoJrmrX6DI',
    authDomain: 'ejemplonumeros-968be.firebaseapp.com',
    messagingSenderId: '926947830123',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
};
